### ISSUE TITLE
bugzilla parsing breaks when bad character is in original description

### ISSUE THREAD

**Issue by sleep-walker** [openSUSE/python-suseapi#3]
```
>>> x = b.get_bug(1045933)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "suseapi/bugzilla.py", line 423, in get_bug
    result = self.get_bugs([bugid], retry)
  File "suseapi/bugzilla.py", line 452, in get_bugs
    data
  File "suseapi/bugzilla.py", line 395, in _handle_parse_error
    raise BugzillaError('Bugzilla has suffered an internal error.')
suseapi.bugzilla.BugzillaError: Generic error: Bugzilla has suffered an internal error.
```

investigation leads to:
```
>>> response_et = ElementTree.fromstring(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 90, column 38
```

relevant portion of the data is:
```
$ sed -n 90p /tmp/problem | hexdump -C
00000000  26 67 74 3b 20 73 75 73  65 52 65 67 69 73 74 65  |&gt; suseRegiste|
00000010  72 52 45 53 2d 31 2e 33  2e 32 2d 31 36 2e 31 2e  |rRES-1.3.2-16.1.|
00000020  6e 6f 61 72 63 68 00 0a                           |noarch..|
00000028
```
You can see `'\0'` character.

**Comment by nijel** [comment]
Should be probably fixed here: https://github.com/openSUSE/python-suseapi/blob/master/suseapi/bugzilla.py#L99
